FROM alpine

COPY slack-notify /

RUN adduser slack-notify --disabled-password && \
  adduser slack-notify slack-notify

RUN chown slack-notify:slack-notify /slack-notify

USER slack-notify

ENTRYPOINT ["/slack-notify"]
